### PR TITLE
make it a synth

### PR DESCRIPTION
**Pull request by mheiber**
`cargo run` goes to the instruction screen.

I won't ruin the mystique by saying more about what happens:

Screenshot 2021-12-25 at 14 58 43

This PR is split into several commits. The first few are just refactors, mostly noops except the one that puts the waves in a vector: that commit makes all the waves the same color.

### CODE REVIEW

**Review by paulcadman — APPROVED** [review]
Now it's the user's responsibility to make it sound beautiful 🥇

**Comment by mheiber** [comment]
> Now it's the user's responsibility to make it sound beautiful 🥇

Theoretically any sound at all could be reproduced with this thing, modulo floating point approximation error

**Comment by mheiber** [comment]
Screenshot 2021-12-25 at 15 55 54

This one sounds pretty good

**Comment by mheiber** [comment]
Screenshot 2021-12-25 at 15 59 57
The glitching at high frequencies looks cool, too

**Pull request merged**
